# Generated by Django 4.0.5 on 2023-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_audiorecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='origin_function',
            field=models.TextField(blank='True', max_length=100),
        ),
    ]
