# Generated by Django 4.0.5 on 2023-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_remove_artifact_level_artifact_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='material',
        ),
        migrations.AddField(
            model_name='artifact',
            name='Level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('experienced', 'Experienced'), ('difficult', 'Difficult'), ('expert', 'Expert')], default='easy', max_length=50),
        ),
    ]
