# Generated by Django 4.0.5 on 2023-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_remove_artifact_material_artifact_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='Level',
        ),
        migrations.AddField(
            model_name='artifact',
            name='additional_facts',
            field=models.TextField(blank='True', max_length=500),
        ),
        migrations.AddField(
            model_name='artifact',
            name='care_requirements',
            field=models.TextField(blank='True', max_length=500),
        ),
        migrations.AddField(
            model_name='artifact',
            name='growth_habits',
            field=models.TextField(blank='True', max_length=500),
        ),
        migrations.AddField(
            model_name='artifact',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Experienced', 'Experienced'), ('Difficult', 'Difficult'), ('Expert', 'Expert')], default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='artifact',
            name='physical_description',
            field=models.TextField(blank='True', max_length=500),
        ),
    ]
